CREATE USER odsconfig_user_Dev WITH ENCRYPTED PASSWORD '******' ;

ALTER DEFAULT PRIVILEGES IN SCHEMA public
   GRANT ALL ON TABLES TO odsconfig_user_Dev;

GRANT ALL PRIVILEGES ON SCHEMA public TO odsconfig_user_Dev;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO odsconfig_user_Dev;
GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA public TO odsconfig_user_Dev;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO odsconfig_user_Dev;
--GRANT ALL PRIVILEGES ON DATABASE "odsconfig_dev" TO odsconfig_user_Dev;

ALTER DEFAULT PRIVILEGES IN SCHEMA ods
   GRANT ALL ON TABLES TO odsconfig_user_Dev;

GRANT ALL PRIVILEGES ON SCHEMA ods TO odsconfig_user_Dev;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA ods TO odsconfig_user_Dev;
GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA ods TO odsconfig_user_Dev;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA ods TO odsconfig_user_Dev;
--GRANT ALL PRIVILEGES ON DATABASE "odsconfig_dev" TO odsconfig_user_Dev;