CREATE USER odslog_user_dev WITH ENCRYPTED PASSWORD '*****' ;

GRANT CONNECT ON DATABASE odslog_dev TO odslog_user_dev;
REVOKE ALL ON ALL TABLES IN SCHEMA public FROM PUBLIC;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT,INSERT,UPDATE,DELETE ON TABLES TO odslog_user_dev;

GRANT SELECT,INSERT,UPDATE,DELETE ON SCHEMA public TO odslog_user_dev;
GRANT SELECT,INSERT,UPDATE,DELETE ON ALL TABLES IN SCHEMA public TO odslog_user_dev;
GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA public TO odslog_user_dev;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO odslog_user_dev;
