CREATE USER ods_user WITH ENCRYPTED PASSWORD 'H!xme_0ds_ah_dev1' ;

ALTER DEFAULT PRIVILEGES IN SCHEMA public
   GRANT ALL ON TABLES TO ods_user;

GRANT ALL PRIVILEGES ON SCHEMA public TO ods_user;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO ods_user;
GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA public TO ods_user;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO ods_user;
GRANT ALL PRIVILEGES ON DATABASE "ODSLog" TO ods_user;
