-- Pivoted Report
WITH CTEPlansAndRates
AS
(
SELECT   P."State" || (CASE WHEN t.RatingArea < 10 THEN '0' || CAST(t.RatingArea AS VARCHAR(3)) ELSE CAST(t.RatingArea AS VARCHAR(3)) END) as "RatingArea"
        ,P."State"
        ,P."HiosPlanID"
        ,P."Carrier" as "CarrierName"
        ,P."CarrierFriendlyName" as "CarrierMarketingName"
        ,P."PlanMarketingName" as "PlanName"
        ,P."PlanType"
        ,P."Metal"
        ,PR."BaseRate"
        ,t.RatingFactor as "RatingFactor"
        ,P."ActuarialValue"
        ,P."HixmeValuePlus0"
        ,P."HixmeValuePlus500"
        ,P."HixmeValuePlus1000"
        ,P."HixmeValuePlus1500"
        ,P."HixmeValuePlus2000"
        ,P."HixmeValuePlus2500"
        ,P."Year"
FROM    "Plans" AS P
INNER
JOIN    "PlanRates" AS PR ON PR."HiosPlanID" = P."HiosPlanID"
                         AND PR."Year" = P."Year"
CROSS
JOIN    unnest(array[PR."AreaFactor01", PR."AreaFactor02", PR."AreaFactor03"
,PR."AreaFactor04", PR."AreaFactor05", PR."AreaFactor06"
,PR."AreaFactor07", PR."AreaFactor08", PR."AreaFactor09"
,PR."AreaFactor10", PR."AreaFactor11", PR."AreaFactor12"
,PR."AreaFactor13", PR."AreaFactor14", PR."AreaFactor15"
,PR."AreaFactor16", PR."AreaFactor17", PR."AreaFactor18"
,PR."AreaFactor19", PR."AreaFactor20", PR."AreaFactor21"
,PR."AreaFactor22", PR."AreaFactor23", PR."AreaFactor24"
,PR."AreaFactor25", PR."AreaFactor26", PR."AreaFactor27"
,PR."AreaFactor28", PR."AreaFactor29", PR."AreaFactor30"
,PR."AreaFactor31", PR."AreaFactor32", PR."AreaFactor33"
,PR."AreaFactor34", PR."AreaFactor35", PR."AreaFactor36"
,PR."AreaFactor37", PR."AreaFactor38", PR."AreaFactor39"
,PR."AreaFactor40", PR."AreaFactor41", PR."AreaFactor42"
,PR."AreaFactor43", PR."AreaFactor44", PR."AreaFactor45"
,PR."AreaFactor46", PR."AreaFactor47", PR."AreaFactor48"
,PR."AreaFactor49", PR."AreaFactor50", PR."AreaFactor51"
,PR."AreaFactor52", PR."AreaFactor53", PR."AreaFactor54"
,PR."AreaFactor55", PR."AreaFactor56", PR."AreaFactor57"
,PR."AreaFactor58", PR."AreaFactor59", PR."AreaFactor60"
,PR."AreaFactor61", PR."AreaFactor62", PR."AreaFactor63"
,PR."AreaFactor64", PR."AreaFactor65", PR."AreaFactor66"
,PR."AreaFactor67"
]) with ordinality as t(RatingFactor, RatingArea)
WHERE   P."Year" = 2019
AND     P."State" = 'CA'
)
SELECT  *
FROM    CTEPlansAndRates
WHERE   "RatingFactor" is not null
ORDER BY "Year", "State", "HiosPlanID", "RatingArea"

-- Flat Repot
SELECT   P."State"
        ,P."HiosPlanID"
        ,P."Carrier" as "CarrierName"
        ,P."CarrierFriendlyName" as "CarrierMarketingName"
        ,P."PlanMarketingName" as "PlanName"
        ,P."PlanType"
        ,P."Metal"
        ,PR."BaseRate"
        ,P."ActuarialValue"
        ,P."HixmeValuePlus0"
        ,P."HixmeValuePlus500"
        ,P."HixmeValuePlus1000"
        ,P."HixmeValuePlus1500"
        ,P."HixmeValuePlus2000"
        ,P."HixmeValuePlus2500"
        ,P."Year"
,PR."AreaFactor01", PR."AreaFactor02", PR."AreaFactor03"
,PR."AreaFactor04", PR."AreaFactor05", PR."AreaFactor06"
,PR."AreaFactor07", PR."AreaFactor08", PR."AreaFactor09"
,PR."AreaFactor10", PR."AreaFactor11", PR."AreaFactor12"
,PR."AreaFactor13", PR."AreaFactor14", PR."AreaFactor15"
,PR."AreaFactor16", PR."AreaFactor17", PR."AreaFactor18"
,PR."AreaFactor19", PR."AreaFactor20", PR."AreaFactor21"
,PR."AreaFactor22", PR."AreaFactor23", PR."AreaFactor24"
,PR."AreaFactor25", PR."AreaFactor26", PR."AreaFactor27"
,PR."AreaFactor28", PR."AreaFactor29", PR."AreaFactor30"
,PR."AreaFactor31", PR."AreaFactor32", PR."AreaFactor33"
,PR."AreaFactor34", PR."AreaFactor35", PR."AreaFactor36"
,PR."AreaFactor37", PR."AreaFactor38", PR."AreaFactor39"
,PR."AreaFactor40", PR."AreaFactor41", PR."AreaFactor42"
,PR."AreaFactor43", PR."AreaFactor44", PR."AreaFactor45"
,PR."AreaFactor46", PR."AreaFactor47", PR."AreaFactor48"
,PR."AreaFactor49", PR."AreaFactor50", PR."AreaFactor51"
,PR."AreaFactor52", PR."AreaFactor53", PR."AreaFactor54"
,PR."AreaFactor55", PR."AreaFactor56", PR."AreaFactor57"
,PR."AreaFactor58", PR."AreaFactor59", PR."AreaFactor60"
,PR."AreaFactor61", PR."AreaFactor62", PR."AreaFactor63"
,PR."AreaFactor64", PR."AreaFactor65", PR."AreaFactor66"
,PR."AreaFactor67"        
FROM    "Plans" AS P
INNER
JOIN    "PlanRates" AS PR ON PR."HiosPlanID" = P."HiosPlanID"
                         AND PR."Year" = P."Year"
WHERE   P."Year" = 2019
AND     P."State" = 'CA'