--DROP VIEW IF EXISTS public.vw_plansrates_updates
CREATE VIEW public.vw_plansrates_updates 
AS    
SELECT
        p."State" as "State"
        ,p."Year" as "plan_year"
        ,cast(null as varchar(30)) as "HIOS Carrier ID"
        ,p."Carrier" as "Carrier"
        ,p."CarrierFriendlyName" as "Carrier Marketing Name"
        ,p."HiosPlanID" as "HIOS Plan ID"
        ,p."PlanDisplayName" as "plan_name"
        ,p."PlanType" as "plan_type"
        ,p."Metal" as "level"
        ,p."IsHSA" as "HSA"
        ,p."IsActive" as "is_active"
        ,p."IsForSale" as "is_for_sale"
        ,p."ServiceAreaID" as "service_area_id"
        ,pr."BaseRate" as "BaseRate"
        ,pr."AreaFactor01" as "RA01"
        ,pr."AreaFactor02" as "RA02"
        ,pr."AreaFactor03" as "RA03"
        ,pr."AreaFactor04" as "RA04"
        ,pr."AreaFactor05" as "RA05"
        ,pr."AreaFactor06" as "RA06"
        ,pr."AreaFactor07" as "RA07"
        ,pr."AreaFactor08" as "RA08"
        ,pr."AreaFactor09" as "RA09"
        ,pr."AreaFactor10" as "RA10"
        ,pr."AreaFactor11" as "RA11"
        ,pr."AreaFactor12" as "RA12"
        ,pr."AreaFactor13" as "RA13"
        ,pr."AreaFactor14" as "RA14"
        ,pr."AreaFactor15" as "RA15"
        ,pr."AreaFactor16" as "RA16"
        ,pr."AreaFactor17" as "RA17"
        ,pr."AreaFactor18" as "RA18"
        ,pr."AreaFactor19" as "RA19"
        ,pr."AreaFactor20" as "RA20"
        ,pr."AreaFactor21" as "RA21"
        ,pr."AreaFactor22" as "RA22"
        ,pr."AreaFactor23" as "RA23"
        ,pr."AreaFactor24" as "RA24"
        ,pr."AreaFactor25" as "RA25"
        ,pr."AreaFactor26" as "RA26"
        ,pr."AreaFactor27" as "RA27"
        ,pr."AreaFactor28" as "RA28"
        ,pr."AreaFactor29" as "RA29"
        ,pr."AreaFactor30" as "RA30"
        ,pr."AreaFactor31" as "RA31"
        ,pr."AreaFactor32" as "RA32"
        ,pr."AreaFactor33" as "RA33"
        ,pr."AreaFactor34" as "RA34"
        ,pr."AreaFactor35" as "RA35"
        ,pr."AreaFactor36" as "RA36"
        ,pr."AreaFactor37" as "RA37"
        ,pr."AreaFactor38" as "RA38"
        ,pr."AreaFactor39" as "RA39"
        ,pr."AreaFactor40" as "RA40"
        ,pr."AreaFactor41" as "RA41"
        ,pr."AreaFactor42" as "RA42"
        ,pr."AreaFactor43" as "RA43"
        ,pr."AreaFactor44" as "RA44"
        ,pr."AreaFactor45" as "RA45"
        ,pr."AreaFactor46" as "RA46"
        ,pr."AreaFactor47" as "RA47"
        ,pr."AreaFactor48" as "RA48"
        ,pr."AreaFactor49" as "RA49"
        ,pr."AreaFactor50" as "RA50"
        ,pr."AreaFactor51" as "RA51"
        ,pr."AreaFactor52" as "RA52"
        ,pr."AreaFactor53" as "RA53"
        ,pr."AreaFactor54" as "RA54"
        ,pr."AreaFactor55" as "RA55"
        ,pr."AreaFactor56" as "RA56"
        ,pr."AreaFactor57" as "RA57"
        ,pr."AreaFactor58" as "RA58"
        ,pr."AreaFactor59" as "RA59"
        ,pr."AreaFactor60" as "RA60"
        ,pr."AreaFactor61" as "RA61"
        ,pr."AreaFactor62" as "RA62"
        ,pr."AreaFactor63" as "RA63"
        ,pr."AreaFactor64" as "RA64"
        ,pr."AreaFactor65" as "RA65"
        ,pr."AreaFactor66" as "RA66"
        ,pr."AreaFactor67" as "RA67"
        ,CAST(null as VARCHAR(100)) as "Update_date"
        ,CAST(null as VARCHAR(1000)) as "plan_notes"
        FROM    "Plans"  as p
        INNER
        JOIN    "PlanRates" as pr ON    pr."Year" = p."Year"
                                AND    pr."HiosPlanID" = p."HiosPlanID"
        WHERE   EXISTS (SELECT 1 FROM public.vw_stage_planrates_raw as s 
                        WHERE s."plan_year" = p."Year" 
                        and s."Hios Plan ID" = p."HiosPlanID" 
                        AND s."State" = p."State");