INSERT INTO public."PlanServiceAreas"("State", "IssuerID", "SourceName", "HiosPlanID", "ServiceAreaID", "ServiceAreaName", "CoverEntireState", "CountyCode", "PartialCounty", "Zipcode", "Year", "IsActive") VALUES ('PA',31609,'LORI','31609PA018','PAS001','Personal Choice PPO',FALSE,101,FALSE,null,2018,TRUE);
INSERT INTO public."PlanServiceAreas"("State", "IssuerID", "SourceName", "HiosPlanID", "ServiceAreaID", "ServiceAreaName", "CoverEntireState", "CountyCode", "PartialCounty", "Zipcode", "Year", "IsActive") VALUES ('PA',31609,'LORI','31609PA018','PAS001','Personal Choice PPO',FALSE,91,FALSE,null,2018,TRUE);
INSERT INTO public."PlanServiceAreas"("State", "IssuerID", "SourceName", "HiosPlanID", "ServiceAreaID", "ServiceAreaName", "CoverEntireState", "CountyCode", "PartialCounty", "Zipcode", "Year", "IsActive") VALUES ('PA',31609,'LORI','31609PA018','PAS001','Personal Choice PPO',FALSE,45,FALSE,null,2018,TRUE);
INSERT INTO public."PlanServiceAreas"("State", "IssuerID", "SourceName", "HiosPlanID", "ServiceAreaID", "ServiceAreaName", "CoverEntireState", "CountyCode", "PartialCounty", "Zipcode", "Year", "IsActive") VALUES ('PA',31609,'LORI','31609PA018','PAS001','Personal Choice PPO',FALSE,29,FALSE,null,2018,TRUE);
INSERT INTO public."PlanServiceAreas"("State", "IssuerID", "SourceName", "HiosPlanID", "ServiceAreaID", "ServiceAreaName", "CoverEntireState", "CountyCode", "PartialCounty", "Zipcode", "Year", "IsActive") VALUES ('PA',31609,'LORI','31609PA018','PAS001','Personal Choice PPO',FALSE,17,FALSE,null,2018,TRUE);
INSERT INTO public."PlanServiceAreas"("State", "IssuerID", "SourceName", "HiosPlanID", "ServiceAreaID", "ServiceAreaName", "CoverEntireState", "CountyCode", "PartialCounty", "Zipcode", "Year", "IsActive") VALUES ('PA',31609,'LORI','31609PA019','PAS001','Personal Choice PPO',FALSE,101,FALSE,null,2018,TRUE);
INSERT INTO public."PlanServiceAreas"("State", "IssuerID", "SourceName", "HiosPlanID", "ServiceAreaID", "ServiceAreaName", "CoverEntireState", "CountyCode", "PartialCounty", "Zipcode", "Year", "IsActive") VALUES ('PA',31609,'LORI','31609PA019','PAS001','Personal Choice PPO',FALSE,91,FALSE,null,2018,TRUE);
INSERT INTO public."PlanServiceAreas"("State", "IssuerID", "SourceName", "HiosPlanID", "ServiceAreaID", "ServiceAreaName", "CoverEntireState", "CountyCode", "PartialCounty", "Zipcode", "Year", "IsActive") VALUES ('PA',31609,'LORI','31609PA019','PAS001','Personal Choice PPO',FALSE,45,FALSE,null,2018,TRUE);
INSERT INTO public."PlanServiceAreas"("State", "IssuerID", "SourceName", "HiosPlanID", "ServiceAreaID", "ServiceAreaName", "CoverEntireState", "CountyCode", "PartialCounty", "Zipcode", "Year", "IsActive") VALUES ('PA',31609,'LORI','31609PA019','PAS001','Personal Choice PPO',FALSE,29,FALSE,null,2018,TRUE);
INSERT INTO public."PlanServiceAreas"("State", "IssuerID", "SourceName", "HiosPlanID", "ServiceAreaID", "ServiceAreaName", "CoverEntireState", "CountyCode", "PartialCounty", "Zipcode", "Year", "IsActive") VALUES ('PA',31609,'LORI','31609PA019','PAS001','Personal Choice PPO',FALSE,17,FALSE,null,2018,TRUE);
INSERT INTO public."PlanServiceAreas"("State", "IssuerID", "SourceName", "HiosPlanID", "ServiceAreaID", "ServiceAreaName", "CoverEntireState", "CountyCode", "PartialCounty", "Zipcode", "Year", "IsActive") VALUES ('PA',33871,'SERFF','33871PA012','PAS001','Keystone HMO',FALSE,101,FALSE,null,2018,TRUE);
INSERT INTO public."PlanServiceAreas"("State", "IssuerID", "SourceName", "HiosPlanID", "ServiceAreaID", "ServiceAreaName", "CoverEntireState", "CountyCode", "PartialCounty", "Zipcode", "Year", "IsActive") VALUES ('PA',33871,'SERFF','33871PA012','PAS001','Keystone HMO',FALSE,91,FALSE,null,2018,TRUE);
INSERT INTO public."PlanServiceAreas"("State", "IssuerID", "SourceName", "HiosPlanID", "ServiceAreaID", "ServiceAreaName", "CoverEntireState", "CountyCode", "PartialCounty", "Zipcode", "Year", "IsActive") VALUES ('PA',33871,'SERFF','33871PA012','PAS001','Keystone HMO',FALSE,45,FALSE,null,2018,TRUE);
INSERT INTO public."PlanServiceAreas"("State", "IssuerID", "SourceName", "HiosPlanID", "ServiceAreaID", "ServiceAreaName", "CoverEntireState", "CountyCode", "PartialCounty", "Zipcode", "Year", "IsActive") VALUES ('PA',33871,'SERFF','33871PA012','PAS001','Keystone HMO',FALSE,29,FALSE,null,2018,TRUE);
INSERT INTO public."PlanServiceAreas"("State", "IssuerID", "SourceName", "HiosPlanID", "ServiceAreaID", "ServiceAreaName", "CoverEntireState", "CountyCode", "PartialCounty", "Zipcode", "Year", "IsActive") VALUES ('PA',33871,'SERFF','33871PA012','PAS001','Keystone HMO',FALSE,17,FALSE,null,2018,TRUE);


SELECT * FROM "PlanServiceAreas" WHERE "IssuerID" = '31609'