ALTER DEFAULT PRIVILEGES IN SCHEMA ods
   GRANT ALL ON TABLES TO odsconfig_user;

GRANT ALL PRIVILEGES ON SCHEMA ods TO odsconfig_user;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA ods TO odsconfig_user;
GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA ods TO odsconfig_user;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA ods TO odsconfig_user;
--GRANT ALL PRIVILEGES ON DATABASE "odsconfig_dev" TO odsconfig_user;
