CREATE USER odsReport_user_dev WITH ENCRYPTED PASSWORD '*****' ;

GRANT CONNECT ON DATABASE odslog_dev TO odsReport_user_dev;
REVOKE ALL ON ALL TABLES IN SCHEMA public FROM PUBLIC;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON TABLES TO odsReport_user_dev;

GRANT SELECT ON SCHEMA public TO odsReport_user_dev;
GRANT SELECT ON ALL TABLES IN SCHEMA public TO odsReport_user_dev;
GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA public TO odsReport_user_dev;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO odsReport_user_dev;
