CREATE TABLE IF NOT EXISTS log."ApiLog" 
(
     "ApiLogId"              SERIAL PRIMARY KEY --INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
    ,"SourceURL"             NOT NULL   VARCHAR(500)
    ,"LoggedInUser"          NOT NULL   VARCHAR(50)
    ,"SessionId"             NULL       VARCHAR(50)
    ,"EntityPublicKey1"      NULL       VARCHAR(50)
    ,"EntityPublicKeyName1"  NULL       VARCHAR(50)
    ,"LambdaName"            NOT NULL   VARCHAR(255)
    ,"CloudWatchRequestId"   NULL       VARCHAR(50)
    ,"APIStartTime"          NOT NULL   TIMESTAMP
    ,"APIEndTime"            NULL       TIMESTAMP
    ,"Request"               NULL       JSONB   DEFAULT '{}'
    ,"ResponseEntities"      NULL       JSONB   DEFAULT '{}'
    ,"APIStatus"             NOT NULL   VARCHAR(20)
    ,"ErrorMessage"          NULL       VARCHAR(500)
    ,"Error"                 NULL       JSONB
    ,"CreatedDtTm"           TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_ApiLog_SourceURL_Date ON log."ApiLog"("SourceURL", "APIStartTime") WITH (fillfactor = 90);
CREATE INDEX IF NOT EXISTS idx_ApiLog_SourceURL_Status ON log."ApiLog"("SourceURL", "APIStatus") WITH (fillfactor = 90);
CREATE INDEX IF NOT EXISTS idx_ApiLog_CreatedDtTm ON log."ApiLog"("CreatedDtTm") WITH (fillfactor = 90);
