CREATE TABLE IF NOT EXISTS log."ApiLog" 
(
     "ApiLogId"              SERIAL PRIMARY KEY --INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
    ,"SourceURL"             VARCHAR(500)   NOT NULL
    ,"LoggedInUser"          VARCHAR(50)    NOT NULL
    ,"SessionId"             VARCHAR(50)    NULL
    ,"EntityPublicKey1"      VARCHAR(50)    NULL
    ,"EntityPublicKeyName1"  VARCHAR(50)    NULL
    ,"LambdaName"            VARCHAR(255)   NOT NULL
    ,"CloudWatchRequestId"   VARCHAR(50)    NULL
    ,"APIStartTime"          TIMESTAMP      NOT NULL
    ,"APIEndTime"            TIMESTAMP      NULL
    ,"Request"               JSONB          NULL
    ,"ResponseEntities"      JSONB          NULL     DEFAULT '{}'
    ,"APIStatus"             VARCHAR(20)    NOT NULL
    ,"ErrorMessage"          VARCHAR(500)   NULL
    ,"Error"                 JSONB          NULL
    ,"CreatedDtTm"           TIMESTAMP      NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_ApiLog_SourceURL_Date ON log."ApiLog"("SourceURL", "APIStartTime") WITH (fillfactor = 90);
CREATE INDEX IF NOT EXISTS idx_ApiLog_SourceURL_Status ON log."ApiLog"("SourceURL", "APIStatus") WITH (fillfactor = 90);
CREATE INDEX IF NOT EXISTS idx_ApiLog_CreatedDtTm ON log."ApiLog"("CreatedDtTm") WITH (fillfactor = 90);
