ALTER DEFAULT PRIVILEGES IN SCHEMA public
   GRANT ALL ON TABLES TO apilog_user;

GRANT ALL PRIVILEGES ON SCHEMA public TO apilog_user;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO apilog_user;
GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA public TO apilog_user;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO apilog_user;

ALTER DEFAULT PRIVILEGES IN SCHEMA ods
   GRANT ALL ON TABLES TO apilog_user;

GRANT ALL PRIVILEGES ON SCHEMA ods TO apilog_user;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA ods TO apilog_user;
GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA ods TO apilog_user;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA ods TO apilog_user;
