service:
  NAME:         ${file(package.json):name, 'untitled-api-service'}
  STAGE:        ${opt:stage, env:NODE_ENV, file(package.json):config.stage, 'int'}
  REGION:       ${opt:region, file(package.json):config.region, 'us-west-2'}
  RUNTIME:      ${file(package.json):config.runtime, 'nodejs6.10'}
  VERSION:      ${file(package.json):version}
  DESCRIPTION:  ${file(package.json):description}

documentation:
  # authorizers:  ${file(schemas/authorizers.yml)}
  description:  Hixme API | ${file(package.json):description}
  models:       ${file(schemas/all.yml)}
  resources:    ${file(schemas/resources.yml)}
  summary:      ${file(package.json):description}
  version:      ${file(package.json):version}

customDomain:
  basePath:             ${file(env.js):getAPIBasePath}
  certificateName:      '*.hixme.com'
  createRoute53Record:  false # leave as-is, unless you know what you're doing
  domainName:           ${file(env.js):getHostname}
  stage:                ${file(env.js):getStage}

serverless-offline:
  prefix: ${file(env.js):getAPIBasePath}

webpack:
  series: true

cognitoPools:
  dev:  arn:aws:cognito-idp:us-west-2:409076796536:userpool/us-west-2_AXPnJkIR9
  int:  arn:aws:cognito-idp:us-west-2:409076796536:userpool/us-west-2_aZ2JNiTZp
  prod: arn:aws:cognito-idp:us-west-2:409076796536:userpool/us-west-2_Guj3GDdPC
