image: node:8.6.0

pipelines:
  default:
    - step:
        caches: [ 'node' ]
        script:
          - node --version
          - npm --version
          - printf "//`node -p \"require('url').parse(process.env.NPM_REGISTRY_URL || 'https://registry.npmjs.org').host\"`/:_authToken=${NPM_TOKEN}\nregistry=${NPM_REGISTRY_URL:-https://registry.npmjs.org}\n" >> ~/.npmrc
          - npm install
          - npm run lint
          - npm test

  branches:
    master:
      - step:
          caches: [ 'node' ]
          script:
            - node --version
            - npm --version
            - printf "//`node -p \"require('url').parse(process.env.NPM_REGISTRY_URL || 'https://registry.npmjs.org').host\"`/:_authToken=${NPM_TOKEN}\nregistry=${NPM_REGISTRY_URL:-https://registry.npmjs.org}\n" >> ~/.npmrc
            - npm install
            - npm run lint
            - npm test
            - npm run deploy:prod

    develop:
      - step:
          caches: [ 'node' ]
          script:
            - node --version
            - npm --version
            - printf "//`node -p \"require('url').parse(process.env.NPM_REGISTRY_URL || 'https://registry.npmjs.org').host\"`/:_authToken=${NPM_TOKEN}\nregistry=${NPM_REGISTRY_URL:-https://registry.npmjs.org}\n" >> ~/.npmrc
            - npm install
            - npm run lint
            - npm test
            - npm run deploy:int