CREATE USER odslog_user WITH ENCRYPTED PASSWORD 'H!xme_0ds_ah_dev1' ;

ALTER DEFAULT PRIVILEGES IN SCHEMA public
   GRANT ALL ON TABLES TO odslog_user;

GRANT ALL PRIVILEGES ON SCHEMA public TO odslog_user;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO odslog_user;
GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA public TO odslog_user;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO odslog_user;
-- GRANT ALL PRIVILEGES ON DATABASE "odslog_dev" TO odslog_user;
